/**
 * @lotos/core — Dark Mode Engine
 *
 * Generates CSS custom properties (variables) for both light and dark mode.
 * Inject the output of `generateCSSVariables()` into the :root {} of your global CSS.
 *
 * Pure TypeScript — no DOM required for generation. The `applyTheme()` function
 * requires a browser DOM environment.
 */

import { colors } from '../tokens/colors.js';
import { typography } from '../tokens/typography.js';
import { spacing, borderRadius } from '../tokens/spacing.js';
import { animation } from '../tokens/animation.js';

export type ColorMode = 'light' | 'dark' | 'system';

/**
 * Generates the full CSS variable block for both dark (default) and light mode.
 * Returns a string you can inject in a <style> tag or write to a .css file.
 */
export function generateCSSVariables(): string {
    return `
/* =============================================
   LotOS UI — CSS Custom Properties (Dark Mode)
   Generated by @lotos/core — DO NOT EDIT MANUALLY
   ============================================= */

:root {
  /* ── Color Scheme ── */
  color-scheme: dark light;

  /* ── Backgrounds ── */
  --lotos-bg-primary:    ${colors.background.primary};
  --lotos-bg-secondary:  ${colors.background.secondary};
  --lotos-bg-card:       ${colors.background.card};
  --lotos-bg-overlay:    ${colors.background.overlay};

  /* ── Foreground / Text ── */
  --lotos-fg-primary:    ${colors.foreground.primary};
  --lotos-fg-secondary:  ${colors.foreground.secondary};
  --lotos-fg-muted:      ${colors.foreground.muted};
  --lotos-fg-inverse:    ${colors.foreground.inverse};

  /* ── Accent ── */
  --lotos-accent:        ${colors.accent.primary};
  --lotos-accent-hover:  ${colors.accent.hover};
  --lotos-accent-active: ${colors.accent.active};
  --lotos-accent-fg:     ${colors.accent.foreground};

  /* ── Brand Raw Colors ── */
  --lotos-deep-navy:     ${colors.deepNavy};
  --lotos-electric-red:  ${colors.electricRed};
  --lotos-ocean-blue:    ${colors.oceanBlue};
  --lotos-white:         ${colors.pureWhite};
  --lotos-lavender:      ${colors.softLavender};

  /* ── Borders ── */
  --lotos-border:        ${colors.border.default};
  --lotos-border-strong: ${colors.border.strong};
  --lotos-border-focus:  ${colors.border.focus};

  /* ── Status Colors ── */
  --lotos-success:       ${colors.status.success};
  --lotos-warning:       ${colors.status.warning};
  --lotos-error:         ${colors.status.error};
  --lotos-info:          ${colors.status.info};

  /* ── Typography ── */
  --lotos-font-sans:     ${typography.fontFamily.sans};
  --lotos-font-mono:     ${typography.fontFamily.mono};
  --lotos-text-xs:       ${typography.fontSize.xs};
  --lotos-text-sm:       ${typography.fontSize.sm};
  --lotos-text-base:     ${typography.fontSize.base};
  --lotos-text-lg:       ${typography.fontSize.lg};
  --lotos-text-xl:       ${typography.fontSize.xl};
  --lotos-text-2xl:      ${typography.fontSize['2xl']};
  --lotos-text-3xl:      ${typography.fontSize['3xl']};
  --lotos-text-4xl:      ${typography.fontSize['4xl']};
  --lotos-text-5xl:      ${typography.fontSize['5xl']};

  /* ── Spacing ── */
  --lotos-space-1:  ${spacing[1]};
  --lotos-space-2:  ${spacing[2]};
  --lotos-space-3:  ${spacing[3]};
  --lotos-space-4:  ${spacing[4]};
  --lotos-space-5:  ${spacing[5]};
  --lotos-space-6:  ${spacing[6]};
  --lotos-space-8:  ${spacing[8]};
  --lotos-space-10: ${spacing[10]};
  --lotos-space-12: ${spacing[12]};
  --lotos-space-16: ${spacing[16]};
  --lotos-space-20: ${spacing[20]};
  --lotos-space-24: ${spacing[24]};

  /* ── Border Radius ── */
  --lotos-radius-sm:   ${borderRadius.sm};
  --lotos-radius:      ${borderRadius.default};
  --lotos-radius-md:   ${borderRadius.md};
  --lotos-radius-lg:   ${borderRadius.lg};
  --lotos-radius-xl:   ${borderRadius.xl};
  --lotos-radius-2xl:  ${borderRadius['2xl']};
  --lotos-radius-full: ${borderRadius.full};

  /* ── Animation ── */
  --lotos-duration-fast:   ${animation.duration.fast};
  --lotos-duration-normal: ${animation.duration.normal};
  --lotos-duration-slow:   ${animation.duration.slow};
  --lotos-ease-out:        ${animation.easing.easeOut};
  --lotos-ease-in-out:     ${animation.easing.easeInOut};
  --lotos-ease-spring:     ${animation.easing.spring};
  --lotos-transition-fast:   ${animation.transition.fast};
  --lotos-transition-normal: ${animation.transition.normal};
  --lotos-transition-slow:   ${animation.transition.slow};
}

/* ─── Light Mode Overrides ─── */
:root[data-theme="light"],
.lotos-light {
  color-scheme: light;

  --lotos-bg-primary:   ${colors.light.background.primary};
  --lotos-bg-secondary: ${colors.light.background.secondary};
  --lotos-bg-card:      ${colors.light.background.card};
  --lotos-bg-overlay:   rgba(0, 0, 0, 0.5);

  --lotos-fg-primary:   ${colors.light.foreground.primary};
  --lotos-fg-secondary: ${colors.light.foreground.secondary};
  --lotos-fg-muted:     ${colors.light.foreground.muted};
  --lotos-fg-inverse:   ${colors.pureWhite};

  --lotos-border:       ${colors.light.border.default};
  --lotos-border-strong:${colors.light.border.strong};
}

/* ─── System Preference Fallback ─── */
@media (prefers-color-scheme: light) {
  :root:not([data-theme]) {
    color-scheme: light;

    --lotos-bg-primary:   ${colors.light.background.primary};
    --lotos-bg-secondary: ${colors.light.background.secondary};
    --lotos-bg-card:      ${colors.light.background.card};
    --lotos-bg-overlay:   rgba(0, 0, 0, 0.5);

    --lotos-fg-primary:   ${colors.light.foreground.primary};
    --lotos-fg-secondary: ${colors.light.foreground.secondary};
    --lotos-fg-muted:     ${colors.light.foreground.muted};
    --lotos-fg-inverse:   ${colors.pureWhite};

    --lotos-border:       ${colors.light.border.default};
    --lotos-border-strong:${colors.light.border.strong};
  }
}

/* ─── Reduced Motion ─── */
@media (prefers-reduced-motion: reduce) {
  * {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}
`.trim();
}

/**
 * Apply a color mode to the document root.
 * Use 'system' to rely on the OS preference.
 * Requires browser environment.
 */
export function applyTheme(mode: ColorMode): void {
    if (typeof document === 'undefined') return;
    const root = document.documentElement;

    if (mode === 'system') {
        root.removeAttribute('data-theme');
    } else {
        root.setAttribute('data-theme', mode);
    }
}

/**
 * Gets the current active theme, resolving 'system' to the actual OS preference.
 */
export function getActiveTheme(): 'light' | 'dark' {
    if (typeof window === 'undefined') return 'dark';
    const attr = document.documentElement.getAttribute('data-theme');
    if (attr === 'light' || attr === 'dark') return attr;
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
}
